server:
  port: 9004

spring:
  application:
    name: dispatcher-service
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    connection-timeout: 5s
  config:
    import: "" # disable spring cloud config import
  cloud:
    config:
      enabled: false # disable spring cloud config client
      uri: http://localhost:9002
      request-read-timeout: 5000
      request-connect-timeout: 5000
      fail-fast: false
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 5000
        multiplier: 1.2
    function:
      definition: pack|label
    stream:
      bindings:
        packlabel-in-0:
          destination: order-accepted
          group: ${spring.application.name}
        packlabel-out-0:
          destination: order-dispatched

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, info, configprops, env, bindings, functions, heapdump, loggers, mappings
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

info:
  system: Polar Bookshop
