apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher-service
  labels:
    app: dispatcher-service
spec:
  selector:
    matchLabels:
      app: dispatcher-service
  template:
    metadata:
      labels:
        app: dispatcher-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "9004"
    spec:
      containers:
        - name: dispatcher-service
          image: dispatcher-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9004
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9004
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9004
            initialDelaySeconds: 5
            periodSeconds: 15
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
          volumeMounts:
            - mountPath: /workspace/config
              name: dispatcher-config-volume
      volumes:
        - name: dispatcher-config-volume
          configMap:
            name: dispatcher-config